services:
  
  redis:
    image: redis:alpine
    command: redis-server --save "" --appendonly no --maxmemory 10mb 
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.14"
          memory: "11MB"

  db_postgres:
    image: postgres:16-alpine
    container_name: db_postgres
    command: postgres -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./createDb.sql:/docker-entrypoint-initdb.d/createDb.sql
    networks:
      - rinha-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

  apiworker1: &apiworker
    build: ../rinha-back-end-2025-worker
    hostname: apiworker
    depends_on:
      - redis
    networks:
      - rinha-network
      - payment-processor
    environment:
      - DB_USER=postgres
      - DB_HOST=db_postgres
      - DB_DATABASE=rinha
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - BASE_URL_DEFAULT=http://payment-processor-default:8080
      - BASE_URL_FALLBACK=http://payment-processor-fallback:8080
      - HEALTH_CHECK=1
    deploy:
      resources:
        limits:
          cpus: "0.07"
          memory: "22MB"

  apiworker2: &workers
    <<: *apiworker
    environment: 
      - DB_USER=postgres
      - DB_HOST=db_postgres
      - DB_DATABASE=rinha
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - BASE_URL_DEFAULT=http://payment-processor-default:8080
      - BASE_URL_FALLBACK=http://payment-processor-fallback:8080
      - HEALTH_CHECK=0

  apiworker3: 
    <<: *workers

  apiworker4: 
    <<: *workers

  apiworker5: 
    <<: *workers

  apiworker6: 
    <<: *workers

  api1: &api
    build: .
    #image:  joaovitorgirardiii/rinha-backend:latest
    hostname: api1
    environment:
      - DB_USER=postgres
      - DB_HOST=db_postgres
      - DB_DATABASE=rinha
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - PORT=3000
    depends_on:
      - db_postgres
      - redis
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.18"
          memory: "25MB"
  api2:
    <<: *api
    hostname: api2

  api3:
    <<: *api
    hostname: api3

  haproxy:
    image: haproxy
    container_name: haproxy
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
      - api3
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 32M

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true