services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "15MB"
  rabbitmq:
    image: rabbitmq:3
    networks:
      - rinha-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "100MB"

  db_postgres:
    image: postgres:16-alpine
    container_name: db-rinha-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./createDb.sql:/docker-entrypoint-initdb.d/createDb.sql
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "40MB"

  apiworker:
    build: ../rinha-back-end-2025-worker
    hostname: apiworker
    depends_on:
      - rabbitmq
    networks:
      - rinha-network
      - payment-processor
    environment:
      - DB_USER=postgres
      - DB_HOST=db-rinha-postgres
      - DB_DATABASE=rinha
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - BASE_URL_DEFAULT=http://payment-processor-default:8080
      - BASE_URL_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "80MB"

  api1: &api
    build: .
    #image:  joaovitorgirardiii/rinha-backend:latest
    hostname: api1
    environment:
      - DB_USER=postgres
      - DB_HOST=db-rinha-postgres
      - DB_DATABASE=rinha
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - PORT=3000
    depends_on:
      - db_postgres
      - rabbitmq
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.225"
          memory: "27.5MB"
  api2:
    <<: *api
    hostname: api2

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true